# Generated by Django 4.2.5 on 2023-09-15 15:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=225)),
                ('services', models.CharField(choices=[('Carpentry', 'Carpentry'), ('Electrician', 'Electrician')], max_length=30)),
                ('skills', models.CharField(choices=[('Carpentry', 'Carpentry'), ('Electrician', 'Electrician')], max_length=30)),
                ('unlisted_skill', models.CharField(max_length=225)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None, unique=True)),
                ('address', models.CharField(max_length=225)),
                ('landmark', models.CharField(max_length=25)),
                ('prefered_location', models.CharField(max_length=225)),
                ('guarantor_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None, unique=True)),
                ('artisan_passport', models.ImageField(upload_to='static/images/')),
                ('guarantor_passport', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
