# Generated by Django 4.2.5 on 2023-09-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='services',
            field=models.CharField(choices=[('Carpentry', 'Carpentry'), ('Electrician', 'Electrician'), ('O', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='skills',
            field=models.CharField(choices=[('Carpentry', 'Carpentry'), ('Electrician', 'Electrician'), ('O', 'Others')], max_length=30),
        ),
    ]
