# Generated by Django 4.2.5 on 2023-10-02 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0002_alter_artisan_gender_alter_artisan_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='guarantor_fullname',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
    ]
