# Generated by Django 4.2.5 on 2023-10-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0005_artisan_artisan_passport_artisan_guarantor_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='artisan_passport',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='guarantor_passport',
        ),
    ]
