# Generated by Django 4.2.5 on 2023-10-08 22:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0007_artisan_artisan_passport_artisan_guarantor_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None, unique=True)),
                ('service_needed', models.CharField(max_length=200)),
                ('special_request', models.TextField(max_length=1500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
