# Generated by Django 4.2.5 on 2023-10-08 22:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None, unique=True),
        ),
    ]
