# Generated by Django 4.2.5 on 2023-10-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0009_alter_artisan_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='guarantor_phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
